#### Functions to create commonly used strings

s.tpx <- function(age, tt) return(if (tt == 1) paste0("{p_{",round(age, 1),"}}") else paste0("{_{", round(tt, 1),"}p_{",round(age, 1),"}}"))
s.tqx <- function(age, tt) return(if (tt == 1) paste0("{q_{",round(age, 1),"}}") else paste0("{_{", round(tt, 1),"}q_{",round(age, 1),"}}"))
s.ktqx <- function(age, kk, tt) return(if (tt == 1) paste0("{_{", round(kk, 1),"}|q_{",round(age, 1),"}}") else paste0("{_{", round(kk, 1),"}|_{",round(tt, 1),"}q_{",round(age, 1),"}}"))
s.ellx <- function(x) return(paste0("\\ell_{", round(x, 1), "}"))
s.frac <- function(num, den) return(paste0("\\frac{", num, "}{", den, "}"))
s.plus <- function(s1, s2) return(paste0(s1, "+", s2))
s.minus <- function(s1, s2) return(paste0(s1, "-", s2))
s.nEx <- function(age, nn) return(paste0("{_{", round(nn, 1),"}E_{",round(age, 1),"}}"))
s.times <- function(s1, s2) return(paste0(s1, "\\cdot ", s2))
s.exp <- function(s1, sexp) return(paste0(s1, "^{",sexp,"}")) 
s.termins <- function(age, nn) return(paste0("\\Ax{\\itop{",age,"}:\\angl{",nn,"}}"))
s.terminsc <- function(age, nn) return(paste0("\\Ax*{\\itop{",age,"}:\\angl{",nn,"}}"))  
s.terminsm <- function(age, nn, mm) return(paste0("\\Ax{\\itop{",age,"}:\\angl{",nn,"}}[\\hspace{0.1in}(", mm, ")]"))
s.insend <- function(age, nn) return(paste0("\\Ax{", age, ":\\angl{", nn, "}}"))
s.insendc <- function(age, nn) return(paste0("\\Ax*{", age, ":\\angl{", nn, "}}")) 
s.insendm <- function(age, nn, mm) return(paste0("\\Ax{", age, ":\\angl{", nn, "}}[(", mm, ")]"))
s.defwl <- function(age, uu) return(paste0("\\Ax[", uu, "|]{", age, "}"))
s.defwlc <- function(age, uu) return(paste0("\\Ax*[", uu, "|]{", age, "}"))
s.defwlm <- function(age, uu, mm) return(paste0("\\Ax[", uu, "|]{", age, "}[(", mm, ")]"))
s.deftermins <- function(age, nn, uu) return(paste0("\\Ax[", uu, "|]{\\itop{",age,"}:\\angl{",nn,"}}"))
s.defterminsc <- function(age, nn, uu) return(paste0("\\Ax*[", uu, "|]{\\itop{",age,"}:\\angl{",nn,"}}"))
s.defterminsm <- function(age, nn, uu, mm) return(paste0("\\Ax[", uu, "|]{\\itop{",age,"}:\\angl{",nn,"}}[\\hspace{0.1in}(", mm, ")]"))
s.termanndue <- function(age, nn) return(paste0("\\ax**{", age, ":\\angl{", nn, "}}"))
s.WLanndue <- function(age) return(paste0("\\ax**{", age, "}"))
s.annguardue <- function(age, nn) return(paste0("\\ax**{\\joint{", age, ":\\angl{", nn, "}}}"))
s.anncertdue <- function(nn) return(paste0("\\ax**{\\angl{", nn, "}}"))
s.contWLann <- function(age) return(paste0("\\ax*{", age, "}"))
s.conttermann <- function(age, nn) return(paste0("\\ax*{", age, ":\\angl{", nn, "}}"))
s.mtermann <- function(age, nn, mm) return(paste0("\\ax**{", age, ":\\angl{", nn, "}}[(", mm, ")]"))
s.mWLann <- function(age, mm) return(paste0("\\ax**{", age, "}[(", mm, ")]"))
s.defWLanndue <- function(age, uu) return(paste0("\\ax**[", uu, "|]{", age, "}"))
s.deftermanndue <- function(age, nn, uu) return(paste0("\\ax**[", uu, "|]{", age, ":\\angl{", nn, "}}"))
s.defguartermanndue <- function(age, nn, uu) return(paste0("\\ax**[", uu, "|]{\\joint{", age, ":\\angl{", nn, "}}}"))
s.defcontWLann <- function(age, uu) return(paste0("\\ax*[", uu, "|]{", age, "}"))
s.defmWLann <- function(age, uu, mm) return(paste0("\\ax**[", uu, "|]{", age, "}[(", mm, ")]"))
s.defconttermann <- function(age, nn, uu) return(paste0("\\ax*[", uu, "|]{", age, ":\\angl{", nn, "}}"))
s.defmtermann <- function(age, nn, uu, mm) return(paste0("\\ax**[", uu, "|]{", age, ":\\angl{", nn, "}}[(", mm, ")]"))
s.npxy <- function(age, age2, nn) return(if (nn == 1) paste0("{p_{",round(age, 1),":",round(age2, 1) ,"}}") else paste0("{_{", round(nn, 1),"}p_{",round(age, 1), ":", round(age2, 1),"}}"))
s.nqxy <- function(age, age2, nn) return(if (nn == 1) paste0("{q_{",round(age, 1),":",round(age2, 1) ,"}}") else paste0("{_{", round(nn, 1),"}q_{",round(age, 1), ":", round(age2, 1),"}}"))
s.npxy2 <- function(age, age2, nn) return(if (nn == 1) paste0("\\px{\\joint{",round(age, 1),":",round(age2, 1) ,"}}") else paste0("\\px[", nn, "]{\\joint{",round(age, 1),":",round(age2, 1) ,"}}"))
s.nqxy2 <- function(age, age2, nn) return(if (nn == 1) paste0("\\qx{\\joint{",round(age, 1),":",round(age2, 1) ,"}}") else paste0("\\qx[", nn, "]{\\joint{",round(age, 1),":",round(age2, 1) ,"}}"))
s.nExy <- function(age, age2, nn) return(paste0("{_{", round(nn, 1),"}E_{",round(age, 1),":", round(age2, 1),"}}"))
s.nExy2 <- function(age, age2, nn) return(paste0("{_{", round(nn, 1),"}E_{\\joint{",round(age, 1),":", round(age2, 1),"}}}"))
s.terminsj2 <- function(age, age2, nn) return(paste0("\\Ax{\\itop{\\overanglebracket{",age,":", age2, "}}:\\angl{",nn,"}}"))
s.terminsl2 <- function(age, age2, nn) return(paste0("\\Ax{\\itop{\\overline{",age,":", age2, "}}:\\angl{",nn,"}}"))
s.WLjt <- function(age, age2) return(paste0("\\Ax{", age, ":", age2, "}"))
s.WLjt2 <- function(age, age2) return(paste0("\\Ax{\\joint{", age, ":", age2, "}}"))
s.termannduejt <- function(age, age2, nn) return(paste0("\\ax**{", age, ":", age2, ":\\angl{", nn, "}}"))
s.termannduelast <- function(age, age2, nn) return(paste0("\\ax**{\\overline{", age, ":", age2, "}:\\angl{", nn, "}}"))
s.annduerev <- function(age, age2) return(paste0("\\ax**{", age, "|", age2, "}"))
s.WLannduejt <- function(age, age2) return(paste0("\\ax**{", age, ":", age2, "}"))
s.WLannduelast <- function(age, age2) return(paste0("\\ax**{\\overline{", age, ":", age2, "}}"))
fbox <- function(ans, ansbox) return(ifelse(ansbox,paste0("\\fbox{", ans, "}"),ans))
  